# Generated by Django 4.1.3 on 2022-11-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manipal1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=3, upload_to=''),
            preserve_default=False,
        ),
    ]
