# Generated by Django 4.1.3 on 2022-11-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manipal1', '0002_category_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='subproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('subproductskey', models.IntegerField()),
                ('productimage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
