# Generated by Django 4.1.3 on 2022-11-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manipal1', '0005_alter_subproducts_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproducts',
            name='uniqueproductid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
