# Generated by Django 4.1.3 on 2022-12-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manipal1', '0006_subproducts_uniqueproductid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=10)),
            ],
        ),
    ]
